### ISSUE TITLE
The request wasn't resolved if response.on('end') was not fired

### ISSUE THREAD

**Issue by Tlezip** [m0rtadelo/ntlm-client#2]
Somehow the event response.on('end') was not fired sometimes, so request was not resolved even the request already finished.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/23031414/168207255-ede43bd2-feb9-458c-9c3f-f79c1f68188f.png">

I think it'd be good if we can handle this case by handle when connection closed. Maybe by adding this.
```
response.on('close', () => {
  if (result.resolve) {
    delete result.resolve;
    res(result);
  }
});
```

**Comment by eviatan** [comment]
Hi @Tlezip @m0rtadelo !
I started yesterday to use this package in my project and I noticed that the long string responses sometime were not completaly catch by the response object. Sometimes it did, sometimes It didn't. 

This drove me to an issue, because if the response.status is 200 I need to JSON.parse() the result (since it is being retrieved in string format) and here nodeJs throw an error because the string is not a valid JSON. When I check the response.body I can see a long string but seems to be cutted, is not the complete string. I can try one or two more times then the body string is complete and also the json.parse works fine.

So, what could be the fix for that? 
Any thoughts?

Thanks in advance for you help.

**Comment by m0rtadelo** [comment]
fixed in v0.0.5

**Comment by eviatan** [comment]
Hello people!!

I already installed v0.0.5

But I still have the issue that long strings sometimes are not being catching. I have 2 internal endpoints being consumed that returns more than seven thousand of characters but the response.body is a string being chopped up before the complete string  is catched. This drives to JSON.parse() to failed. I'm using Insomnia to test the endpoint directly and It works as expected there. But in the nodejs project using node-client-ntlm the response is not complete.

What could be the issue?
